org: reminder
service: reminder-api
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  httpApi:
    cors: true
  environment:
    DB_URL: ${env:DB_URL}



functions:
  - ${file(aws/lambdas/doctors.yml)}
  - ${file(aws/lambdas/reminders.yml)}
