org: reminder
service: reminder-api
frameworkVersion: "3"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

useDotenv: true

custom:
  secrets: ${ssm:/aws/reference/secretsmanager/prod/api}
  #serverless-offline:
  #  httpPort: 3001

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: us-east-1
  httpApi:
    cors: true
  environment:
    DB_URL: ${self:custom.secrets.DB_URL, env:DB_URL}
    REGION: ${self:custom.secrets.REGION, env:REGION}
    WHATSAPP_ENDPOINT: ${self:custom.secrets.WHATSAPP_ENDPOINT, env:WHATSAPP_ENDPOINT}
    WHATSAPP_TOKEN: ${self:custom.secrets.WHATSAPP_TOKEN, env:WHATSAPP_TOKEN}
    ACCESS_TOKEN_SECRET: ${self:custom.secrets.ACCESS_TOKEN_SECRET, env:ACCESS_TOKEN_SECRET}

  iam:
    role:
      statements:
        - ${file(aws/iam.yml):iam-SecretManagerRolePolicies}
        - ${file(aws/iam.yml):iam-SQSRolePolicies}


functions:
  - ${file(aws/lambdas/doctors.yml)}
  - ${file(aws/lambdas/reminders.yml)}
  - ${file(aws/lambdas/schedulers.yml)}
  - ${file(aws/lambdas/redirects.yml)}
  - ${file(aws/lambdas/replies.yml)}
  - ${file(aws/sqs-workers/message-worker.yml)}

resources:
  - ${file(aws/resources/sqsQueue.yml)}
